---
- hosts: localhost
  name: Guake terminal & minor bashrc changes
  become: yes

  vars_prompt:
    - name: "Target"
      prompt: "Where do you want to put guake config?"
      default: "/home/neko/.bashrc"
      private: no
    


  tasks:

    - name: Apt guake
      apt:
        update_cache: yes
        name: 'guake'


     - name: Change bashrc
       shell: cat /home/neko/Downloads/initial-ansible-playbook-master/modules/guake-terminal/bashrc.txt > {{ Target }}


 #   - name: Change bashrc
 #    shell: cat /home/neko/Downloads/initial-ansible-playbooks-master/modules/guake-terminal/bashrc.txt# > /home/neko/.bashrc