---
- hosts: localhost
  name: Emacs26 configuration
  become: yes
  
  vars_prompt:
    - name: "Copy"
      prompt: "Where do you want to copy emacs config from?"
      default: "/home/neko/Downloads/initial-ansible-playbooks-master/modules/emacs/dotfiles/"
      private: no


    - name: "Paste"
      prompt: "Where do you want to paste the emacs config?"
      default: "/home/neko/.emacs.d/"
      private: no


  tasks:

    - name: Adding PPA
      apt_repository:
        repo: ppa:kelleyk/emacs


    - name: Install emacs
      apt:
        name: emacs26


    - name: Copy config
      copy:
        src: "{{ Copy }}"
        dest: "{{ Paste }}"

